### ISSUE TITLE
Cannot bind argument to parameter 'LinterIssue' because it is null error shown when no issues

### ISSUE THREAD

**Issue by TylerLeonhardt** [JustinGrote/Super-Duper-Linter#8]
Looks like this needs to be an empty collection, or accept null.

[Example build](https://github.com/TylerLeonhardt/powershell-code-server/runs/817226889#step:4:16)
![image](https://user-images.githubusercontent.com/2644648/85972994-515c9680-b986-11ea-8973-4c293aca2652.png)

**Comment by JustinGrote** [comment]
Good catch, I usually used the pipeline on this to work on one or more but so changed it and it regressed, I'll get a fix in tomorrow.

**Comment by JustinGrote** [comment]
@TylerLeonhardt should update in the next 5 minutes, watch for the docker timestamp to update:
https://hub.docker.com/layers/jgrote/superduperlinter/preview/images/sha256-e7a203cc9845ddc609837983d8ec0ee3e563faf6e6dc4907eaa85ab2a5c09564?context=repo

**Comment by TylerLeonhardt** [comment]
LGTM :) 

https://github.com/TylerLeonhardt/powershell-code-server/runs/819616915
